### PR TITLE
fix: upgrade tinyglobby

### LINKED ISSUE #119: Slow packaging of pnpm workspaces project
### What version of pkg are you using?

6.0.0, 5.16.0

### Which version(s) of pkg work for you?

5.15.0

### What version of Node.js are you using?

20.18.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node20-linux-x64

### Describe the Bug

I have a pnpm project using workspaces. build time is significantly slower in pkg 5.16 onwards. Our project builds in 22 seconds using pkg 5.15, and 35 *minutes* when using pkg 5.16 or later. 

### Expected Behavior

Build time should be similar for both. Or at least in the same order of magnitude. 

### To Reproduce

Unzip the reproduce.zip folder. 

[reproduce.zip](https://github.com/user-attachments/files/17587988/reproduce.zip)

run these commands:
```bash
pnpm install
time pnpm -r artifacts
```
then in packages/foo/package.json change the version to ~5.16.0, and repeat the above commands.
For me this are the execution times:
|pkg version|build time|
|--|--|
|~5.15.0|0m5.618s| 
|~5.16.0|0m28.320s|
|~6.0.0|0m30.630s|

### PR DESCRIPTION
**Pull request by SuperchupuDev**
fixes #119

the problem with glob usage in this project is that `globSync` is called multiple times which isn't optimal, as it forces `tinyglobby` to traverse the filesystem multiple times. in theory, `globSync` could be called just once during the walking process, but that would be a bigger refactor, although a possible one

EDIT: this pr upgrades tinyglobby, ignore the text below this

it looks like under a default config most patterns passed to `globSync` aren't even globs, so this PR avoids unnecessary `globSync` calls when none of the patterns are globs

<details><summary>screenshot of patterns passed to tinyglobby in 6.1.0, each log is a different glob call</summary>

image
</details> 

locally (windows) this change makes it faster than 5.15.0, with the reproduction from #119 taking 25s in 5.15.0 and 13s in latest with the change (latest without the change took too long to measure)

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
ci is failing, will debug tomorrow

**Comment by robertsLando** [comment]
Could you also test if there are improvements with the `test-80-compression-node-opcua` test?

**Comment by robertsLando** [comment]
I also created https://github.com/yao-pkg/pkg/pull/122, I would like to compare performances of tests in this two PR

**Comment by SuperchupuDev** [comment]
from my local tests in the zip repro of #119 this should be faster than #122, since the unnecesary glob calls were still present back then

**Comment by robertsLando** [comment]
In fact seems this is faster 👍🏼

File: lib/walker.ts [hunk 1]
```diff
@@ -194,7 +195,22 @@ function upon(p: string, base: string) {
...
+    } else if (existsSync(pattern)) {
+      paths.push(pattern);
+    }
+  }
+
+  if (patterns.length !== 0) {
+    return [...paths, ...globSync(patterns, { absolute: true, dot: true })];
+  }
+
+  return paths;
```
Comment (robertsLando) [inline lib/walker.ts:213]: I'm wondering why tinyglobby cannot use `isDynamicPattern` his own by default before starting parsing a pattern?

Comment (SuperchupuDev) [reply lib/walker.ts:213]: consistency shenanigans, but mainly just that i don't think it will be needed once its optimization pr gets fixed and lands

**Comment by SuperchupuDev** [comment]
okay i see why at least some tests fail, it's due to this project using directory expansion, which means that globbing `dir` is the same as globbing `dir/**`. `dir` itself is technically not dynamic so it gets skipped which shouldn't happen

**Comment by robertsLando** [comment]
@SuperchupuDev Yep understood, could you fix that?

**Comment by SuperchupuDev** [comment]
trying

**Comment by SuperchupuDev** [comment]
okay, fixing it would just make all patterns dynamic, we need a better solution. there needs to be a refactor in the walker logic so that all patterns are pushed into an array and then when all of them are collected call `globSync` once

**Comment by robertsLando** [comment]
@SuperchupuDev Could you do that?

**Comment by robertsLando** [comment]
@SuperchupuDev Makes sense, agreee

**Comment by robertsLando** [comment]
@SuperchupuDev News on this?

**Comment by SuperchupuDev** [comment]
been busy with university, i have to debug and figure out why vite's tests fail with the upcoming version, could try today

**Comment by SuperchupuDev** [comment]
@robertsLando changed this pr to the upcoming tinyglobby version instead, can you compare performance again?

**Comment by SuperchupuDev** [comment]
it's 4 minutes on fast-glob as well: https://github.com/yao-pkg/pkg/actions/runs/11703987586/job/32595478258?pr=122#step:7:20

**Comment by SuperchupuDev** [comment]
although this pr should solve the perf issue in #119, for the record, if you want to avoid unnecesary globbing one solution can be setting `expandDirectories` to `false` in tinyglobby's options, then doing what this pr did before i force pushed. it'd be a breaking change though as users would have to replace some of their patterns i.e. `src` with `src/**`

**Comment by robertsLando** [comment]
Ok thanks for that! I would not go for that option as I think there will be too much edge cases to handle and I'm quite sure it could cause some unexpected issues I don't want to deal with right now. We can merge this if it's ready 👍🏼

**Comment by robertsLando** [comment]
I correct myself: we can merge this once you have a release for tinyglobby :)

**Comment by robertsLando** [comment]
@SuperchupuDev ok will wait so, thanks! :)

**Comment by SuperchupuDev** [comment]
good news - the new fdir version was released today. i'll work on tinyglobby starting next week

**Comment by SuperchupuDev** [comment]
the new optimizer was completely rewritten for the second time and merged on tinyglobby's main branch. all that's left for a release is to fix a completely unrelated bug that many have been asking me to fix :+1: should be out really soon!!

**Comment by robertsLando** [comment]
@SuperchupuDev Good news! Thanks for the update, let me know when the last fix is ready and I can merge this :)

**Comment by SuperchupuDev** [comment]
@robertsLando the new release is out!! i've updated my pr. sorry it took so long :P

**Comment by robertsLando** [comment]
@SuperchupuDev no need to be sorry man, it's OSS and I appreciate every help even if it take some time 🙏🏼 😄 

Thanks!

**Review by robertsLando — APPROVED** [review]
